# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'StockMaster' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for StockMaster
  
  pod 'Alamofire', '~> 5.5'
  pod 'SwiftSpinner', '~> 2.2'
  pod 'PromiseKit', '~> 6.16'
  pod 'SwiftyJSON', '~> 5.0'
  pod 'RealmSwift', '~> 10.22'

end
