# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'StockDetails' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for StockDetails
    pod 'Alamofire'
    pod 'SwiftyJSON'
   pod 'SwiftSpinner', '~> 2.2'

end
